language:
  - python
python:
  - 3.5
notifications:
  email: false
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-dev.txt
script:
  - py.test
