# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='block',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Block'),
        ),
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'Incomplete'), (1, 'Ready for Review'), (2, 'Needs Reworking'), (3, 'Complete'), (4, 'Flagged for review')], default=0, verbose_name='State'),
        ),
    ]
