# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160830_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionorder',
            old_name='module',
            new_name='topic',
        ),
    ]
