# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_syllabus_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
