# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20161003_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_order',
        ),
        migrations.AddField(
            model_name='block',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
