# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'classes'},
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='users',
        ),
    ]
