# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20161104_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionorder',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
