# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_questionorder_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionorder',
            name='moderator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
