# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_questionorder_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('open', models.BooleanField(default=True)),
                ('due_date', models.DateField(null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='questionorder',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='questionorder',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='questionorder',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='questionorder',
            name='topic',
        ),
        migrations.DeleteModel(
            name='QuestionOrder',
        ),
    ]
