# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_questionorder_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.AddField(
            model_name='question',
            name='additional_info_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='option',
            name='content',
            field=models.TextField(default=''),
        )
    ]
