# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20161116_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
