# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20161111_1035'),
        ('core', '0020_auto_20161117_2321'),
    ]

    operations = [
    ]
