# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20161118_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
