# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 22:48
from __future__ import unicode_literals

from django.db import migrations
from core.models import Question
import uuid


def gen_uuid(apps, schema_editor):

    for row in Question.objects.all():
        row.uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_question_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
