# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 23:12
from __future__ import unicode_literals

from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    Group.objects.bulk_create([
        Group(name='Content Creator'),
        Group(name='Content Moderator'),
        Group(name='Syllabus Creator'),
        Group(name='Platform Manager')
    ])

    # Add all permissions for platform manager
    manager = Group.objects.get(name='Platform Manager')
    permissions = list(Permission.objects.all())
    manager.permissions.add(*permissions)

    # Add task and question permissions for content creator/moderator
    content = Group.objects.get(name='Content Creator')
    moderator = Group.objects.get(name='Content Moderator')
    permissions = list(Permission.objects.filter(codename__in=[
        'add_comment',
        'change_comment',
        'change_question',
        'change_task'
    ]))
    content.permissions.add(*permissions)
    moderator.permissions.add(*permissions)

    # Add syllabus creator permissions
    syllabus = Group.objects.get(name='Syllabus Creator')
    permissions = list(Permission.objects.filter(codename__in=[
        'add_block',
        'change_block',
        'delete_block',
        'add_class',
        'change_class',
        'delete_class',
        'add_grade',
        'change_grade',
        'delete_grade',
        'add_subject',
        'change_subject',
        'delete_subject',
        'add_syllabus',
        'change_syllabus',
        'delete_syllabus',
        'add_task',
        'change_task',
        'delete_task',
        'add_topic',
        'change_topic',
        'delete_topic'
    ]))
    syllabus.permissions.add(*permissions)


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            'Content Creator',
            'Content Moderator',
            'Syllabus Creator',
            'Platform Manager'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_task_description'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
