# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20161119_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='content_json',
            field=models.TextField(default=''),
        ),
    ]
