# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_question_additional_info_content_json'),
        ('core', '0026_auto_20161119_2312'),
    ]

    operations = [
    ]
